---
- hosts: servers
  strategy: free
  roles:
    - fedora-server
  become: yes
  become_user: "{{ ansible_user | default('root') }}"
  vars:
    ansible_ssh_private_key_file: "{{ '.keys/'+inventory_hostname+'_id_rsa' }}"