---

- name: Disable SELinux
  command: "setenforce 0 && sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux"

# The br_netfilter module is required for kubernetes installation. 
# Enable this kernel module so that the packets traversing the bridge are processed by iptables for filtering and for port forwarding, and the kubernetes pods across the cluster can communicate with each other.
- name: Enable br_netfilter Kernel Module
  command: "modprobe br_netfilter && echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

- name: Disable SWAP
  command: sed -i '/ swap /s/^/#/' /etc/fstab

