---

- name: ubuntu install python3-pip 
  apt:
    name: python3-pip
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install python3-pip
  package: name=python3-pip state=present
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Checkout dockervpn
  git:
    repo: 'https://github.com/Izual13/dockvpn.git'
    dest: "~/dockervpn/"

- name: Build an image
  docker_image:
    name: vpn
    build:
      path: "~/dockervpn/"
      pull: yes
    source: build

- name: VPN container
  docker_container:
    name: vpn
    image: vpn
    state: started
    restart_policy: always
    privileged: true
    ports:
    - "25:25/tcp"
    - "123:123/udp"

- name: download config
  shell: "docker exec vpn /bin/cat /etc/openvpn/client.ovpn"
  retries: 5
  delay: 10
  register: config
  until: config.rc == 0
  
- name: print config
  debug:
    msg: "{{config.stdout}}"  

- name: save config  
  local_action: 
    copy content={{ config.stdout }} dest=.keys/client.ovpn


  








