---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install git
  dnf:
    name: git
    state: latest

- name: install tmux
  dnf:
    name: tmux
    state: latest

- name: install docker
  dnf:
    name: "https://download.docker.com/linux/fedora/28/x86_64/stable/Packages/docker-ce-18.06.1.ce-3.fc28.x86_64.rpm"
    state: latest

- name: start daemon docker
  systemd:
    state: started
    name: docker

- name: install docker-compose
  dnf:
    name: docker-compose
    state: latest

- name: install wireshark
  dnf:
    name: wireshark
    state: latest

- name: install Java
  dnf:
    name: java
    state: latest
