#ubuntu-servers
---

- name: Install Docker and role dependencies
  apt:
    name: "{{ item }}"
    state: "present"
    install_recommends: False
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"

- name: Get upstream APT GPG key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: "hkp://pool.sks-keyservers.net"
    state: "present"

- name: Configure upstream APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
    state: "present"
    update_cache: True

- name: Install Docker
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - "docker-ce"

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"
