---
- name: Set authorized key, removing all the authorized key already set
  authorized_key:
    user: root
    key: "{{ lookup('file', '.keys/'+inventory_hostname+'_id_rsa.pub') }}"
    state: present
    exclusive: yes