---
- name: Set authorized key, removing all the authorized key already set
  authorized_key:
    user: "{{ansible_user}}"
    key: "{{ lookup('file', '.keys/'+ (inventory_hostname | replace('.', '_')) +'_id_rsa.pub') }}"
    state: present
    exclusive: yes