---

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install git
  dnf:
    name: git
    state: latest

- name: install tmux
  dnf:
    name: tmux
    state: latest

- name: install docker
  dnf:
    name: "https://download.docker.com/linux/fedora/29/x86_64/stable/Packages/docker-ce-18.09.1-3.fc29.x86_64.rpm"
    state: latest

- name: install docker-compose
  dnf:
    name: docker-compose
    state: latest

- service:
    name: docker
    state: started