---

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install git
  dnf:
    name: git
    state: latest

- name: install tmux
  dnf:
    name: tmux
    state: latest

- name: Verify the key, using a fingerprint, before import
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/fedora/gpg
    fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35

- name: install dnf-plugins-core
  dnf:
    name: "dnf-plugins-core"
    state: latest

- name: add docker repo
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: install docker ce
  dnf:
    name: "docker-ce"
    state: latest

- name: install docker cli
  dnf:
    name: "docker-ce-cli"
    state: latest    

- name: install containerd.io
  dnf:
    name: "containerd.io"
    state: latest
  notify: ["Start Docker"]

- name: install docker-compose
  dnf:
    name: docker-compose
    state: latest

- name: install iotop
  dnf:
    name: iotop
    state: latest
