---

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install git
  dnf:
    name: git
    state: latest

- name: install tmux
  dnf:
    name: tmux
    state: latest

- name: Verify the key, using a fingerprint, before import
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/fedora/gpg
    fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35

- name: install container io
  dnf:
    name: "https://download.docker.com/linux/fedora/35/x86_64/stable/Packages/containerd.io-1.5.10-3.1.fc35.x86_64.rpm"
    state: latest

- name: install docker cli
  dnf:
    name: "https://download.docker.com/linux/fedora/35/x86_64/stable/Packages/docker-ce-cli-20.10.13-3.fc35.x86_64.rpm"
    state: latest

- name: install docker
  dnf:
    name: "https://download.docker.com/linux/fedora/35/x86_64/stable/Packages/docker-ce-20.10.13-3.fc35.x86_64.rpm"
    state: latest
  notify: ["Start Docker"]

- name: install docker-compose
  dnf:
    name: docker-compose
    state: latest

- name: install iotop
  dnf:
    name: iotop
    state: latest
